from aiogram.fsm.state import State, StatesGroup


class AdminStates(StatesGroup):
    WAITING_NEW_PRICE = State()
    WAITING_NEW_TOKEN_PRICE = State()
    WAITING_SETTING_VALUE = State()

    WAITING_CATEGORY_NAME = State()
    WAITING_CATEGORY_ICON = State()
    WAITING_CATEGORY_BUTTON_COLUMNS = State()

    WAITING_PRODUCT_NAME = State()
    WAITING_PRODUCT_FIXED_PRICE = State()
    WAITING_PRODUCT_UNIT_PRICE = State()
    WAITING_PRODUCT_MIN_QTY = State()
    WAITING_PRODUCT_MAX_QTY = State()
    WAITING_PRODUCT_BUTTON_COLUMNS = State()

    WAITING_CHANNEL_TITLE = State()
    WAITING_CHANNEL_USERNAME = State()
    WAITING_CHANNEL_INVITE_LINK = State()

    WAITING_PRODUCT_DISCOUNT_PERCENT = State()

    WAITING_USER_SEARCH = State()

    WAITING_COUPON_PERCENT = State()

    WAITING_BROADCAST_MESSAGE = State()

    WAITING_VPN_PANEL_NAME = State()
    WAITING_VPN_PANEL_URL = State()
    WAITING_VPN_PANEL_USERNAME = State()
    WAITING_VPN_PANEL_PASSWORD = State()
    WAITING_VPN_PANEL_INBOUND_ID = State()

    WAITING_PRODUCT_VPN_LIMIT = State()
    WAITING_PRODUCT_VPN_DURATION = State()

    WAITING_PAYMENT_PROVIDER_API_URL = State()
    WAITING_PAYMENT_PROVIDER_API_KEY = State()
    WAITING_PAYMENT_PROVIDER_EDIT_API_URL = State()
    WAITING_PAYMENT_PROVIDER_EDIT_API_KEY = State()
